name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to AWS ECR
        uses: kshitijsigh01
        with:
          aws-region: <stockholm>
        
